// Copyright 2026 The OpenTacit Authors
// SPDX-License-Identifier: Apache-2.0

// Package digest renders "what your team discovered this week" — the A2
// delivery surface from docs/delivery/low-intrusion-plan.md: a non-interrupting
// weekly (or any-window) markdown summary of technique activity, built from
// the same computation the Insights dashboard uses. Post it to chat, mail
// it, or read it in a terminal — it is deliberately plain markdown.
package digest

import (
	"fmt"
	"strings"
	"time"

	"github.com/opentacit/tacit/internal/product"
	"github.com/opentacit/tacit/internal/registry/insights"
	"github.com/opentacit/tacit/internal/registry/models"
)

// Render produces the digest for one computed overview.
func Render(o insights.Overview, techniques []models.Technique) string {
	var b strings.Builder
	from := o.Window.Start.Format("Jan 2")
	to := o.Now.Format("Jan 2, 2006")
	fmt.Fprintf(&b, "# %s digest: %s to %s\n\n", product.Name(), from, to)

	// --- headlines ---
	b.WriteString("## Headlines\n\n")
	fmt.Fprintf(&b, "- **%d suggestions shown**, **%d adopted**%s",
		o.Funnel.Shown, o.Funnel.Adopted, deltaPhrase(o.Funnel.Adopted, o.PrevFunnel.Adopted))
	if rate, measured := o.Funnel.HelpedRate(); measured {
		fmt.Fprintf(&b, ", helped rate **%.0f%%** (n=%d)", rate*100, o.Funnel.Adopted)
	}
	b.WriteString("\n")
	if o.NewTechniques > 0 {
		fmt.Fprintf(&b, "- **%d new technique%s** went live or entered review\n",
			o.NewTechniques, plural(o.NewTechniques))
	}
	if share, n := insights.OrgShare(o.ShownByScope); n > 0 {
		fmt.Fprintf(&b, "- **%.0f%%** of delivered suggestions used org-scoped techniques\n", share*100)
	}
	if o.ActiveCohorts > 0 {
		fmt.Fprintf(&b, "- %d cohort%s active\n", o.ActiveCohorts, plural(o.ActiveCohorts))
	}
	b.WriteString("\n")

	// --- fresh knowledge ---
	if len(o.Fresh) > 0 {
		b.WriteString("## New & newly active\n\n")
		for _, c := range o.Fresh {
			badge := "newly active"
			if c.New {
				badge = "new"
			}
			fmt.Fprintf(&b, "- **%s** _(%s, %s, %s)_\n", c.Technique.Name, badge,
				insights.OrLabel(c.Technique.Scope, "general"), insights.OrLabel(c.Technique.Provenance, "curated"))
		}
		b.WriteString("\n")
	}

	// --- movers ---
	if len(o.Fastest) > 0 {
		b.WriteString("## Largest adoption increases\n\n")
		for _, c := range o.Fastest {
			fmt.Fprintf(&b, "- **%s**: %d adoption%s (%+d compared with the previous period)\n",
				c.Technique.Name, c.Funnel.Adopted, plural(c.Funnel.Adopted), c.Velocity())
		}
		b.WriteString("\n")
	}
	if len(o.Best) > 0 {
		b.WriteString("## Highest helped rates\n\n")
		for _, c := range o.Best {
			if rate, ok := c.Funnel.HelpedRate(); ok {
				fmt.Fprintf(&b, "- **%s**: helped %.0f%% (n=%d)\n", c.Technique.Name, rate*100, c.Funnel.Adopted)
			}
		}
		b.WriteString("\n")
	}

	// --- provenance story ---
	if len(o.AdoptedByProvenance) > 0 {
		b.WriteString("## Where adopted knowledge came from\n\n")
		for _, m := range o.AdoptedByProvenance {
			fmt.Fprintf(&b, "- %s: %d\n", m.Label, m.Count)
		}
		b.WriteString("\n")
	}

	// --- health ---
	var health []string
	for _, c := range o.Decayed {
		health = append(health, fmt.Sprintf("- **%s** has lower recent outcomes. Review or retire it.", c.Name))
	}
	for _, m := range o.Dismissals {
		if m.Label == "didnt-work" && m.Count > 0 {
			health = append(health, fmt.Sprintf("- %d 'didn't work' dismissal%s recorded", m.Count, plural(m.Count)))
		}
	}
	if drafts := countDrafts(techniques); drafts > 0 {
		health = append(health, fmt.Sprintf("- %d draft%s awaiting review in the [Drafts lane](/drafts)", drafts, plural(drafts)))
	}
	if len(health) > 0 {
		b.WriteString("## Needs attention\n\n" + strings.Join(health, "\n") + "\n\n")
	}

	b.WriteString("---\n_Generated by `tacit digest` from aggregate and cohort data._\n")
	return b.String()
}

// Build computes and renders in one step.
func Build(techniques []models.Technique, events []models.FeedbackEvent, now time.Time, windowKey string) string {
	w := insights.WindowByKey(windowKey, now, insights.Earliest(events))
	return Render(insights.Compute(techniques, events, now, w), techniques)
}

func deltaPhrase(cur, prev int) string {
	switch d := cur - prev; {
	case d > 0:
		return fmt.Sprintf(" (+%d vs the previous window)", d)
	case d < 0:
		return fmt.Sprintf(" (%d vs the previous window)", d)
	default:
		return ""
	}
}

func countDrafts(techniques []models.Technique) int {
	n := 0
	for _, c := range techniques {
		if c.Status == "draft" {
			n++
		}
	}
	return n
}

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}
