// Copyright 2026 The OpenTacit Authors
// SPDX-License-Identifier: Apache-2.0

// Package pricing turns token counts into dollars for the harnesses that do not
// report their own.
//
// Claude Code hands `tacit statusline` the session's real cost, so on that one
// client the money on the Usage page is measured. The agent routes nine
// harnesses. The other eight report tokens and no dollars, so a member on Codex
// or Cursor was reading a blank where the cost should be.
//
// A table of published rates closes it, the way ccusage does. The rates are
// generated by cmd/tacit-genprices from the providers' own published pricing,
// so the authority is the provider rather than anything written down here.
//
// The cost of that is honesty about two things, and both are enforced here
// rather than left to the caller:
//
//  1. AN ESTIMATE IS NOT A MEASUREMENT. Estimate returns a figure and the page
//     keeps it in its own field, never added to what a harness measured. A total
//     that mixed the two silently would be the most expensive kind of wrong
//     number on this page: specific, plausible and unattributable.
//
//  2. A PRICE GOES STALE. AsOf is the day this table was read off the vendors'
//     own pages, and the page prints it. A model with no row prices NOTHING
//     rather than borrowing a neighbour's rate, and a vendor whose published
//     price is a RANGE — Gemini's Pro tiers, which vary with prompt size — is
//     left out for the same reason: half a price is not a cheaper price, it is
//     a guess.
//
// Rates are USD per million tokens, keyed by modelid.Key so a dated build, a
// gateway route and a Bedrock arn all find the same row.
package pricing

import "github.com/opentacit/tacit/internal/modelid"

// AsOf is the day the prices in force were read. It is rendered beside every
// estimate, because a member comparing this month against last needs to know
// whether the prices moved under them.
//
// It reports the SNAPSHOT's day (published.go), which is the one a schedule can
// keep current. handAsOf is the day the fallback table below was last checked
// against the vendors' own pages, and it only answers where the snapshot is
// silent.
var AsOf = asOf()

const handAsOf = "2026-09-12"

func asOf() string {
	if published.AsOf != "" {
		return published.AsOf
	}
	return handAsOf
}

// Rate is one model's published price in USD per million tokens.
//
// Four numbers rather than two, because the input side is not one price. A cache
// read costs a tenth of fresh input on most models and a cache write costs a
// premium over it, and on a session that is 94% cache reads the difference
// between pricing the split and pricing the sum is an order of magnitude.
type Rate struct {
	In         float64 `json:"in"`          // fresh input, the part that missed the cache
	CacheWrite float64 `json:"cache_write"` // written into the cache
	CacheRead  float64 `json:"cache_read"`  // served from it
	Out        float64 `json:"out"`
}

// rates is the FALLBACK table, keyed by modelid.Key: the models the generated
// snapshot does not carry, and the answer of last resort if that file ever
// fails to parse. The snapshot is checked first (published.go).
//
// Anthropic: platform.claude.com/docs/en/about-claude/pricing. Cache writes are
// the FIVE-MINUTE rate (1.25x input). The transcript records one cache-creation
// count and does not say which TTL it was written at, so a session using the
// one-hour cache (2x) is estimated low. Named here because an unstated
// assumption in a cost figure is the kind of thing that gets found out.
//
// OpenAI: developers.openai.com/api/docs/pricing, which now prints a cache
// writes column of its own at 1.25x input. It did not always: these rows read
// "a write is billed as fresh input" long after that stopped being true, which
// is the whole argument for generating the snapshot rather than typing it.
//
// Google: ai.google.dev/gemini-api/docs/pricing, context-cache rate as the read.
// Only the models with ONE published rate are here; the Pro tiers and the newer
// Flash builds are priced in ranges that depend on prompt size, and a range
// cannot be resolved from a token count.
var rates = map[string]Rate{
	// Anthropic
	"anthropic/claude-fable-5-1":  {In: 10, CacheWrite: 12.50, CacheRead: 0.25, Out: 50},
	"anthropic/claude-mythos-5-1": {In: 10, CacheWrite: 12.50, CacheRead: 0.25, Out: 50},
	"anthropic/claude-fable-5":    {In: 10, CacheWrite: 12.50, CacheRead: 1, Out: 50},
	"anthropic/claude-mythos-5":   {In: 10, CacheWrite: 12.50, CacheRead: 1, Out: 50},
	"anthropic/claude-opus-5":     {In: 5, CacheWrite: 6.25, CacheRead: 0.50, Out: 25},
	"anthropic/claude-opus-4-8":   {In: 5, CacheWrite: 6.25, CacheRead: 0.50, Out: 25},
	"anthropic/claude-opus-4-7":   {In: 5, CacheWrite: 6.25, CacheRead: 0.50, Out: 25},
	"anthropic/claude-opus-4-6":   {In: 5, CacheWrite: 6.25, CacheRead: 0.50, Out: 25},
	"anthropic/claude-opus-4-5":   {In: 5, CacheWrite: 6.25, CacheRead: 0.50, Out: 25},
	"anthropic/claude-opus-4-1":   {In: 15, CacheWrite: 18.75, CacheRead: 1.50, Out: 75},
	"anthropic/claude-opus-4":     {In: 15, CacheWrite: 18.75, CacheRead: 1.50, Out: 75},
	"anthropic/claude-sonnet-5":   {In: 2, CacheWrite: 2.50, CacheRead: 0.20, Out: 10},
	"anthropic/claude-sonnet-4-6": {In: 3, CacheWrite: 3.75, CacheRead: 0.30, Out: 15},
	"anthropic/claude-sonnet-4-5": {In: 3, CacheWrite: 3.75, CacheRead: 0.30, Out: 15},
	"anthropic/claude-sonnet-4":   {In: 3, CacheWrite: 3.75, CacheRead: 0.30, Out: 15},
	"anthropic/claude-haiku-4-5":  {In: 1, CacheWrite: 1.25, CacheRead: 0.10, Out: 5},
	"anthropic/claude-haiku-3-5":  {In: 0.80, CacheWrite: 1, CacheRead: 0.08, Out: 4},

	// OpenAI
	"openai/gpt-6-astra":   {In: 10, CacheWrite: 12.50, CacheRead: 1, Out: 50},
	"openai/gpt-5-6-sol":   {In: 4, CacheWrite: 5, CacheRead: 0.40, Out: 20},
	"openai/gpt-5-6-terra": {In: 2, CacheWrite: 2.50, CacheRead: 0.20, Out: 12},
	"openai/gpt-5-6-luna":  {In: 0.20, CacheWrite: 0.25, CacheRead: 0.02, Out: 1.20},
	"openai/gpt-5-5":       {In: 5, CacheWrite: 5, CacheRead: 0.50, Out: 30},
	"openai/gpt-5-4":       {In: 2.50, CacheWrite: 2.50, CacheRead: 0.25, Out: 15},
	"openai/gpt-5-4-mini":  {In: 0.75, CacheWrite: 0.75, CacheRead: 0.075, Out: 4.50},
	"openai/gpt-5-4-nano":  {In: 0.20, CacheWrite: 0.20, CacheRead: 0.02, Out: 1.25},
	"openai/gpt-5-2":       {In: 1.75, CacheWrite: 1.75, CacheRead: 0.175, Out: 14},
	"openai/gpt-5-1":       {In: 1.25, CacheWrite: 1.25, CacheRead: 0.125, Out: 10},
	"openai/gpt-5":         {In: 1.25, CacheWrite: 1.25, CacheRead: 0.125, Out: 10},
	"openai/gpt-5-mini":    {In: 0.25, CacheWrite: 0.25, CacheRead: 0.025, Out: 2},
	"openai/gpt-5-nano":    {In: 0.05, CacheWrite: 0.05, CacheRead: 0.005, Out: 0.40},
	"openai/gpt-4-1":       {In: 2, CacheWrite: 2, CacheRead: 0.50, Out: 8},
	"openai/gpt-4-1-mini":  {In: 0.40, CacheWrite: 0.40, CacheRead: 0.10, Out: 1.60},
	"openai/gpt-4-1-nano":  {In: 0.10, CacheWrite: 0.10, CacheRead: 0.025, Out: 0.40},
	"openai/gpt-4o":        {In: 2.50, CacheWrite: 2.50, CacheRead: 1.25, Out: 10},
	"openai/gpt-4o-mini":   {In: 0.15, CacheWrite: 0.15, CacheRead: 0.075, Out: 0.60},

	// Google — single-rate models only.
	"google/gemini-3-5-flash":      {In: 1.50, CacheWrite: 1.50, CacheRead: 0.15, Out: 9},
	"google/gemini-3-5-flash-lite": {In: 0.30, CacheWrite: 0.30, CacheRead: 0.03, Out: 2.50},
	"google/gemini-2-5-flash":      {In: 0.30, CacheWrite: 0.30, CacheRead: 0.03, Out: 2.50},
	"google/gemini-2-5-flash-lite": {In: 0.10, CacheWrite: 0.10, CacheRead: 0.01, Out: 0.40},
}

// Lookup finds a model's published rate. raw is whatever the harness said; it is
// canonicalised the same way every other model reading on the page is, so a
// dated build and a gateway route find the row their family has.
//
// A miss is not an error and not a zero — it is the honest answer for a model
// nobody published a price for, and every caller must treat it as "no estimate"
// rather than "free".
func Lookup(raw string) (Rate, bool) {
	key := modelid.Key(raw)
	if r, ok := published.Models[key]; ok {
		return r, true
	}
	r, ok := rates[key]
	return r, ok
}

// Estimate prices one session's tokens. fresh, cacheWrite and cacheRead are the
// three classes of input the transcript reports apart (capture.TokenUsage); out
// is what the model produced.
//
// A model with no published rate estimates nothing, and says so, rather than
// returning a confident zero.
func Estimate(raw string, fresh, cacheWrite, cacheRead, out int) (float64, bool) {
	r, ok := Lookup(raw)
	if !ok {
		return 0, false
	}
	const perToken = 1_000_000.0
	usd := (float64(fresh)*r.In +
		float64(cacheWrite)*r.CacheWrite +
		float64(cacheRead)*r.CacheRead +
		float64(out)*r.Out) / perToken
	return usd, true
}

// Models is how many models can be priced at all, for a page that wants to say
// how far its coverage reaches without listing every row. The two sources
// overlap, so this counts the union rather than adding them.
func Models() int {
	seen := make(map[string]bool, len(published.Models)+len(rates))
	for k := range published.Models {
		seen[k] = true
	}
	for k := range rates {
		seen[k] = true
	}
	return len(seen)
}
